# observability/jaeger.yml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jaeger
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jaegertracing.github.io/helm-charts
    chart: jaeger
    targetRevision: "0.71.0"
    helm:
      values: |
        provisionDataStore:
          cassandra: false
          elasticsearch: true
        elasticsearch:
          replicas: 1
        agent:
          enabled: true
        collector:
          enabled: true
        query:
          enabled: true
          ingress:
            enabled: true
            hosts:
              - jaeger.yourdomain.com
  destination:
    server: https://kubernetes.default.svc
    namespace: observability