# helm/employee-app/values.yaml
replicaCount: 2

image:
  repository: ghcr.io/your-org/employee-app
  pullPolicy: IfNotPresent
  tag: ""

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "100"
  hosts:
    - host: employee-app.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: employee-app-tls
      hosts:
        - employee-app.yourdomain.com

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

mysql:
  enabled: true
  auth:
    rootPassword: "secure-root-password"
    database: "employeedb"
    username: "employeeuser"
    password: "secure-password"
  persistence:
    enabled: true
    size: 8Gi